[logger]
version = 1
disable_existing_loggers = false

[logger.handlers.ingestion_console]
class = "logging.StreamHandler"
level = "INFO"
formatter = "ingestion_default"
stream = "ext://sys.stdout"

[logger.formatters.ingestion_default]
format = "%(asctime)s - %(name)-15s - %(filename)-20s [%(levelname)-8s]: %(message)s"
datefmt = "%Y-%m-%d %H:%M:%S"

[logger.loggers.ingestion]
handlers = ["ingestion_console"]
level = "INFO"